### ISSUE TITLE
[process] Final checklist before submitting for review

### ISSUE THREAD

**Issue by ihkihk** [ihkihk/viz-js-loans#20]
- [x] Clean all js-lint issues indicated by c9.io
- [x] Test access from rawgit and c9 server
- [x] Make sure readme.md is up-to-date
